### ISSUE TITLE
Multiple NoClassDefFoundErrors with REI installed [1.18]

### ISSUE THREAD

**Issue by jbredwards** [Low-Drag-MC/LDLib#1]
[latest.log](https://github.com/Low-Drag-MC/LDLib/files/9115262/latest.log)

**Comment by MaxNeedsSnacks** [comment]
This is... a bit of a bigger issue. JEI doesn't pass mouse scrolling or key presses to recipes (only clicks), so LDLib uses JEI's internals to forcefully pass that event through to their wrappers. These JEI internals aren't implemented (or wrapped) by REI, so things crash.

I don't think there's particularly much that can be done here to add compat with REI apart from explicitly making an REI plugin (and disabling the JEI plugin when REI is installed) as it likely doesn't make sense for REI to *wrap the entirety of JEI's recipe GUI and layouts*, or hoping that JEI will add this functionality in the future so these hacks become unnecessary

**Comment by vfyjxf** [comment]
And Rei does not appear to support jei 10. If Rei is to be supported, #4 may need to be heavily modified and the supported version of jei rolled back.

**Comment by Yefancy** [comment]
compatible now
