### ISSUE TITLE
crash with JEI 10.1.0.223

### ISSUE THREAD

**Issue by donoya** [Low-Drag-MC/LDLib#2]
I'm playing with a bunch of other mods, but the ones affecting the crash seem to be JEI and this. I posted about it on JEI's issue tracker and they said to report it here.
Crash report: https://pastebin.com/CDHaJi5e

**Comment by Yefancy** [comment]
LDLib use the 9.7.0 of the jei, we will fix it when the 10.0+ becomes a release vesrion

**Comment by wiloxe** [comment]
I'm having same issue at the moment since Fantasy's Furniture changed and added a requirement of JEI version to be alpha version.

**Comment by vfyjxf** [comment]
> I'm having same issue at the moment since Fantasy's Furniture changed and added a requirement of JEI version to be alpha version.

I've added Jei 10 compatibility, check it out in #4.

**Comment by Yefancy** [comment]
compatible
